name: Deploy to Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Spring Boot jar
        run: ./mvnw clean package -DskipTests

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_LOGIN }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /semstoreweb/app/sEmStoreWeb
            git pull origin main
            ./mvnw clean package -DskipTests
            docker-compose down
            docker-compose up -d --build
